# This is your configuration for your first flag
first-flag:
  variations: # All possible return value for your feature flag
    A: false
    B: true
  targeting: # If you want to target a subset of your users in particular
    - name: Development environment
      query: key eq "user_id" and env eq "dev"
      percentage:
        A: 0
        B: 100
    # - name: Production environment
    #   query: key eq "user_id" and env eq "prod"
    #   percentage:
    #     A: 0
    #     B: 100
  defaultRule: # When no targeting match we use the defaultRule
    variation: A
  metadata:
    issue_link: https://github.com/thomaspoignant/go-feature-flag/issues/XXX
    description: this is my first feature flag

# A second example of a flag configuration
second-flag:
  variations:
    A: "valueA"
    B: "valueB"
    defaultValue: "a default value"
  targeting: # If you want to target a subset of your users in particular
    - name: Development environment
      query: key eq "user_id" and env eq "dev"
      variation: B
    - name: Production environment
      query: key eq "user_id" and env eq "prod"
      variation: A
  defaultRule:
    name: default rule
    variation: defaultValue
  version: "12"
  experimentation:
    start: 2024-01-01T00:00:00.1-05:00
    end: 2024-01-31T00:00:00.1-05:00
